{
  "openapi": "3.0.3",
  "info": {
    "title": "Online Learning RESTful API",
    "description": "RESTful API Specification For Online Learning Backend Application",
    "version": "1.0.0",
    "contact": {
      "name": "Fikran Akbar",
      "email": "fikranakbar756@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://{environment}/api",
      "variables": {
        "environment": {
          "default": "localhost:8000",
          "description": "Online Learning RESTful API Server",
          "enum": [
            "localhost:8000"
          ]
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Authentication",
      "description": "API list of user authentication such login, register, logout"
    },
    {
      "name": "Course - Category",
      "description": "API to Show all courses category and get courses by category"
    },
    {
      "name": "Course - Popular Course",
      "description": "API to get the most popular courses, limit to 5"
    },
    {
      "name": "Course - Search Course",
      "description": "API to search course by keyword"
    },
    {
      "name": "Course - Detail Course",
      "description": "API list for show course detail and get user course progression "
    }
  ],
  "externalDocs": {
    "description": "Fikran Akbar's Github",
    "url": "https://github.com/FikranAkbar"
  },
  "paths": {
    "/users/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Login user with email and password",
        "description": "Login user with registered email and password. The API will return token to access protected route",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                }
              },
              "example": {
                "email": "fikranakbar756@gmail.com",
                "password": "password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login Successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "email": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "token": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "200",
                  "message": "OK",
                  "data": {
                    "email": "fikranakbar756@gmail.com",
                    "name": "Fikran Akbar",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlrcmFuIEFrYmFyIiwiZW1haWwiOiJmaWtyYW5ha2Jhcjc1NkBnbWFpbC5jb20ifQ._tSgZvD3rl9gBwunH4JgwcHn1adyTMYSR6N2uHuWsqw"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Login failed. Email and password must be filled",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": 400,
                  "message": "BAD REQUEST",
                  "data": "Login failed. Email must be type of email. Email and password must be filled"
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/403-Forbidden"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Register user with email, password, name, date_birth, gender",
        "description": "Register user with email, password, name, date_birth, gender. This API will not auto-login the user, so will not return token for accessed protected route",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true,
                    "minLength": 8
                  },
                  "name": {
                    "type": "string",
                    "maxLength": 100,
                    "required": true
                  },
                  "date_birth": {
                    "type": "string",
                    "required": true
                  },
                  "gender": {
                    "type": "string",
                    "enum": ["Male", "Female"]
                  }
                }
              },
              "example": {
                "email": "fikranakbar756@gmail.com",
                "password": "password",
                "name": "Fikran Akbar",
                "date_birth": "2000-07-01",
                "gender": "Male"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Register user successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "message": "OK",
                  "data": {
                    "id": 1,
                    "name": "Fikran Akbar",
                    "email": "fikranakbar756@gmail.com"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Register user failed. All field must be filled or the given data was invalid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "Email error": {
                    "value": {
                      "status": 400,
                      "message": "BAD REQUEST",
                      "data": "Register failed. Email must be type of email"
                    }
                  },
                  "Password minimum length error": {
                    "value": {
                      "status": 400,
                      "message": "BAD REQUEST",
                      "data": "Register failed. Password must be 8 character minimum"
                    }
                  },
                  "Empty field error": {
                    "value": {
                      "status": 400,
                      "message": "BAD REQUEST",
                      "data": "Register failed. All field must be filled"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Logout user with JSON Web Token (JWT)",
        "description": "Logout user with JSON Web Token (JWT)",
        "responses": {
          "200": {
            "description": "Logout success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "message": "OK",
                  "data": null
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-Unauthorized"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses": {
      "get": {
        "tags": ["Course - Search Course"],
        "description": "Search course by keyword",
        "summary": "Search course by keyword",
        "parameters": [
          {
            "name": "keyword",
            "in": "query",
            "required": true,
            "description": "keyword for searching course names"
          }
        ],
        "responses": {
          "200": {
            "description": "Search course success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CourseCardSchema"
                },
                "examples": {
                  "CourseCardDataExample": {
                    "$ref": "#/components/examples/CourseCardDataExample"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Search course failed, query cannot be empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": 400,
                  "message": "BAD REQUEST",
                  "data": "Query cannot be empty"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-NotFound"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses/categories": {
      "get": {
        "tags": ["Course - Category"],
        "summary": "Get all courses category",
        "description": "Get all courses category",
        "responses": {
          "200": {
            "description": "Get all courses category success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "category_name": {
                            "type": "string"
                          },
                          "category_photo_url": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "message": "OK",
                  "data": [
                    {
                      "id": 1,
                      "category_name": "Entrepreneurship",
                      "category_photo_url": ""
                    },
                    {
                      "id": 2,
                      "category_name": "Marketing",
                      "category_photo_url": ""
                    },
                    {
                      "id": 3,
                      "category_name": "English",
                      "category_photo_url": ""
                    },
                    {
                      "id": 4,
                      "category_name": "Creative",
                      "category_photo_url": ""
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-NotFound"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses/categories/:categoryId": {
      "get": {
        "tags": ["Course - Category"],
        "summary": "Get courses by category id",
        "description": "Get all course from category by category id",
        "parameters": [
          {
            "name": "categoryId",
            "in": "path",
            "schema": {
              "type": "number"
            },
            "required": true,
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Get course by category success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CourseCardSchema"
                },
                "examples": {
                  "CourseCardDataExample": {
                    "$ref": "#/components/examples/CourseCardDataExample"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Category id was invalid, so the category was not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "null"
                    }
                  }
                },
                "example": {
                  "status": 400,
                  "message": "BAD REQUEST",
                  "data": null
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-NotFound"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses/popular": {
      "get": {
        "tags": ["Course - Popular Course"],
        "summary": "Get the most popular courses",
        "description": "Get the most popular courses, limit to 5",
        "responses": {
          "200": {
            "description": "Get the most popular courses success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CourseCardSchema"
                },
                "examples": {
                  "CourseCardDataExample": {
                    "$ref": "#/components/examples/CourseCardDataExample"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-NotFound"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses/:courseId": {
      "get": {
        "tags": ["Course - Detail Course"],
        "description": "Get course detail by course id. Client can send JWT token and user id in request body. If the user id inside JWT token matches with user id client send in request body, the field 'already_owned' in the response become true.",
        "summary": "Get course detail by course id",
        "parameters": [
          {
            "name": "categoryId",
            "in": "path",
            "required": true,
            "example": 5
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string"
                  },
                  "user_id": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlrcmFuIEFrYmFyIiwiZW1haWwiOiJmaWtyYW5ha2Jhcjc1NkBnbWFpbC5jb20ifQ._tSgZvD3rl9gBwunH4JgwcHn1adyTMYSR6N2uHuWsqw",
                "user_id": 1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Get course detail by course id success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailCourseSchema"
                },
                "examples": {
                  "Detail course of owned course": {
                    "$ref": "#/components/examples/DetailOwnedCourseExample"
                  },
                  "Detail course": {
                    "$ref": "#/components/examples/DetailCourseExample"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-NotFound"
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    },
    "/courses/:courseId/progression": {
      "get": {
        "tags": ["Course - Detail Course"],
        "summary": "Get course progression of a user",
        "description": "Get course progression of a user",
        "responses": {
          "200": {
            "description": "Get course progression of a user success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "user_id": {
                          "type": "number"
                        },
                        "course_id": {
                          "type": "number"
                        },
                        "last_unlocked_module": {
                          "type": "number"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "message": "OK",
                  "data": {
                    "user_id": 1,
                    "course_id": 1,
                    "last_unlocked_module": 1
                  }
                }
              }
            }
          },
          "403": {
            "description": "Get course progression failed. User was not owned the course",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "number"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": 403,
                  "message": "FORBIDDEN",
                  "data": "Get course progression failed. User was not owned the course"
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/500-InternalServerError"
          }
        }
      }
    }
  },
  "components": {
    "responses": {
      "401-Unauthorized": {
        "description": "Unauthorized, Token already expired",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "null"
                }
              }
            },
            "example": {
              "status": 401,
              "message": "UNAUTHORIZED",
              "data": null
            }
          }
        }
      },
      "403-Forbidden": {
        "description": "Wrong credentials, such like email, password, etc",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "string"
                }
              }
            },
            "example": {
              "status": 403,
              "message": "FORBIDDEN",
              "data": "Wrong credentials, such like email, password, etc"
            }
          }
        }
      },
      "404-NotFound": {
        "description": "Data not found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "null"
                }
              }
            },
            "example": {
              "status": "404",
              "message": "NOT FOUND",
              "data": null
            }
          }
        }
      },
      "500-InternalServerError": {
        "description": "Internal server error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "number"
                },
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "string"
                }
              }
            },
            "example": {
              "status": 500,
              "message": "INTERNAL SERVER ERROR",
              "data": "Error detail"
            }
          }
        }
      }
    },
    "schemas": {
      "CourseCardSchema": {
        "type": "object",
        "properties": {
          "status": {
            "type": "number"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number"
                },
                "course_name": {
                  "type": "string"
                },
                "expert_name": {
                  "type": "string"
                },
                "photo_url": {
                  "type": "string"
                },
                "average_rate": {
                  "type": "number"
                }
              }
            }
          }
        }
      },
      "ExpertShortDetailSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "photo": {
            "type": "string"
          },
          "average_rate": {
            "type": "number"
          }
        }
      },
      "ExpertLongDetailSchema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "photo": {
            "type": "string"
          },
          "average_rate": {
            "type": "number"
          },
          "total_course": {
            "type": "number"
          },
          "total_participant": {
            "type": "number"
          }
        }
      },
      "DetailCourseSchema": {
        "type": "object",
        "properties": {
          "status": {
            "type": "number"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "course_id": {
                "type": "number"
              },
              "course_name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "photo_url": {
                "type": "string"
              },
              "contents": {
                "type": "string"
              },
              "average_rate": {
                "type": "number"
              },
              "current_participant": {
                "type": "number"
              },
              "maximum_participant": {
                "type": "number"
              },
              "already_owned": {
                "type": "boolean"
              },
              "expert": {
                "$ref": "#/components/schemas/ExpertShortDetailSchema"
              }
            }
          }
        }
      }
    },
    "examples": {
      "CourseCardDataExample": {
        "description": "Course Card Data Example",
        "value": {
          "status": 200,
          "message": "OK",
          "data": [
            {
              "id": 1,
              "course_name": "Intro to Enterpreneurship",
              "photo_url": "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1174&q=80",
              "average_rate": 0,
              "expert_name": "Ray Robinson"
            },
            {
              "id": 5,
              "name": "Intermediate to Enterpreneurship",
              "photo_url": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
              "average_rate": 0,
              "expert_name": "Brielle Hutchinson"
            },
            {
              "id": 9,
              "name": "Expert to Enterpreneurship",
              "photo_url": "https://images.unsplash.com/photo-1533749871411-5e21e14bcc7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
              "average_rate": 0,
              "expert_name": "Ray Robinson"
            }
          ]
        }
      },
      "DetailOwnedCourseExample": {
        "description": "Detail course when the course already owned by user",
        "value": {
          "status": 200,
          "message": "OK",
          "data": {
            "course_id": 5,
            "course_name": "Intermediate to Entrepreneurship",
            "description": "Deskripsi Intermediate to Enterpreneurship Deskripsi Intermediate to Enterpreneurship Deskripsi Intermediate to Enterpreneurship",
            "photo_url": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "contents": "4x e-learning modules and 4x webinar sessions",
            "average_rate": 4.5,
            "current_participant": 10,
            "maximum_participant": 30,
            "already_owned": true,
            "expert": {
              "name": "Brielle Hutchinson",
              "photo": "https://thumbs.dreamstime.com/b/young-woman-avatar-cartoon-character-profile-picture-young-brunette-woman-short-hair-avatar-cartoon-character-vector-149728784.jpg",
              "average_rate": 4.5
            }
          }
        }
      },
      "DetailCourseExample": {
        "description": "Detail course when the course was not owned by user",
        "value": {
          "status": 200,
          "message": "OK",
          "data": {
            "course_id": 5,
            "course_name": "Intermediate to Entrepreneurship",
            "description": "Deskripsi Intermediate to Enterpreneurship Deskripsi Intermediate to Enterpreneurship Deskripsi Intermediate to Enterpreneurship",
            "photo_url": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "contents": "4x e-learning modules and 4x webinar sessions",
            "average_rate": 4.5,
            "current_participant": 10,
            "maximum_participant": 30,
            "already_owned": false,
            "expert": {
              "name": "Brielle Hutchinson",
              "photo": "https://thumbs.dreamstime.com/b/young-woman-avatar-cartoon-character-profile-picture-young-brunette-woman-short-hair-avatar-cartoon-character-vector-149728784.jpg",
              "average_rate": 4.5
            }
          }
        }
      },
      "ExpertShortDetailExample": {
        "description": "Expert detail in short version",
        "value": {
          "name": "Brielle Hutchinson",
          "photo": "https://thumbs.dreamstime.com/b/young-woman-avatar-cartoon-character-profile-picture-young-brunette-woman-short-hair-avatar-cartoon-character-vector-149728784.jpg",
          "average_rate": 4.5
        }
      },
      "ExpertLongDetailExample": {
        "description": "Expert detail in long version",
        "value": {
          "name": "Brielle Hutchinson",
          "description": "Saya adalah expert Ray Robinson di platform mojadipro",
          "photo": "https://thumbs.dreamstime.com/b/young-woman-avatar-cartoon-character-profile-picture-young-brunette-woman-short-hair-avatar-cartoon-character-vector-149728784.jpg",
          "average_rate": 4.5,
          "total_course": 3,
          "total_participant": 60
        }
      }
    }
  }
}